### ISSUE TITLE
Use mathjs or a handwritten parser+interpreter for plotFormula

### ISSUE THREAD

**Issue by M4GNV5** [sezanzeb/JsPlot3D#27]
Using eval is generally considered bad. Using regexes on code is not very good style either. Using [math.js's eval](http://mathjs.org/docs/expressions/parsing.html) or writing a simple [infix to postfix converter](http://scriptasylum.com/tutorials/infix_postfix/algorithms/infix-postfix/) could fix this issue.

**Comment by sezanzeb** [comment]
:+1: ty
